# Generated by Django 3.1.6 on 2021-03-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DisclaimerAdmin',
            new_name='Disclaimer',
        ),
    ]
